In [1]:
import requests
import json
from pprint import pprint
import numpy as np
import pandas as pd

In [2]:
base = "https://v4p4sz5ijk.execute-api.us-east-1.amazonaws.com/anbdata/airports/traffic/departure-stats?api_key=1d820730-a43a-11e9-8ba5-19b2d1f43f82&airports=&states=CAN&format=json&Year="


#print(requests.get(base).json())
#response = requests.get(base).json()
#print(json.dumps(response, indent=4, sort_keys=True))

response = requests.get(base)
print(response.url)

https://v4p4sz5ijk.execute-api.us-east-1.amazonaws.com/anbdata/airports/traffic/departure-stats?api_key=1d820730-a43a-11e9-8ba5-19b2d1f43f82&airports=&states=CAN&format=json&Year=

In [3]:
data = response.json()
# pprint(data)

In [4]:
len(data)

3165

In [5]:
connections = []
departures = []
name = []
year = []

for i in range(len(data)):
    connections.append(data[i]["Connections"])
    departures.append(data[i]["Departures"])
    name.append(data[i]["AirportName"])
    year.append(data[i]["Year"])

In [6]:
# year

In [7]:
new_df = pd.DataFrame({"AirportName" : name, "Number of Departures" : departures, "Number of Connections" : connections, "Year" : year })
new_df.to_csv("CSV_files/Airport-data.csv")

In [8]:
new_df

,AirportName,Number of Departures,Number of Connections,Year
0,WEBEQUIE,365,4,2018
1,BIG TROUT LAKE,863,6,2018
2,PICKLE LAKE,626,5,2018
3,MUSKRAT DAM,488,4,2018
4,KITCHENER,355,1,2018
5,BRANDON,497,1,2018
6,FOND DU LAC,21,3,2018
7,STONY RAPIDS,12,2,2018
8,POINTS NORTH LAND,11,2,2018
9,URANIUM CITY,6,1,2018
10,MAKKOVIK,624,2,2018
11,HOPEDALE,625,3,2018
12,CHARLO,319,4,2018
13,ST ANTHONY,716,5,2018
14,BONAVENTURE,1010,2,2018
15,ST HUBERT,1440,5,2018
16,STEPHENVILLE,170,6,2018
17,FORT CHIPEWYAN,419,2,2018
18,MASSET,256,1,2018
19,BELLA BELLA,665,3,2018
20,PORT HARDY,1257,2,2018
21,POWELL RIVER,1838,1,2018
22,BELLA COOLA,477,2,2018
23,FORT NORMAN,1409,2,2018
24,FORT FRANKLIN,835,2,2018
25,KASABONIKA,625,6,2018
26,FORT GOOD HOPE,836,5,2018
27,AKLAVIK,573,1,2018
28,GATINEAU,446,1,2018
29,NATASHQUAN,1309,5,2018
...,...,...,...,...
3135,NORTH BAY,2686,5,2003
3136,PEACE RIVER,35,1,2007
3137,SANIKILUAQ,209,4,2005
3138,DEER LAKE,4946,19,2016
3139,MUNICIPAL,261,1,2007
3140,MUSKRAT DAM,966,4,2013
3141,FORT NORMAN,1300,2,2006
3142,LLOYDMINSTER,557,2,2004
3143,MOOSONEE,1364,3,2003
3144,FORT ST JOHN,2786,5,2011
3145,HAY RIVER,1126,4,2003
3146,SACHIGO LAKE,411,7,2004
3147,CHURCHILL FALLS,567,3,2018
3148,LYTTON,122,1,2006
3149,AKLAVIK,503,1,2012
3150,GODS NARROWS,155,4,2009
3151,PANGNIRTUNG,1896,6,2009
3152,BELLA BELLA,1180,4,2014
3153,CAMPBELL RIVER,4327,7,2005
3154,WEMINDJI,720,2,2012
3155,GJOA HAVEN,1046,11,2003
3156,SANIKILUAQ,209,2,2003
3157,WINNIPEG JAMES ARMSTRONG RICHARDSON INTL,31295,83,2004
3158,FORT MCPHERSON,470,1,2016
3159,CAMBRIDGE BAY,1394,13,2003
3160,CHURCHILL FALLS,565,4,2017
3161,MAKKOVIK,576,2,2008
3162,FORT NELSON,812,3,2006
3163,PICKLE LAKE,480,7,2007
3164,AUPALUK,741,3,2005